# This docker compose file works with kbase-ui - specifically the kbase-dev
# network that allows proxying service requests from kbase-ui and the narrative.
version: "3.8"
networks:
  kbase-dev:
    name: kbase-dev
    external: true
services:
  staging_service:
    hostname: staging_service
    build:
      context:  .
    ports:
      # TODO: should be port 5000 to match other kbase services
      - "3010:3000"
    volumes:
      - "./data:/kb/deployment/lib/src/data"
      - "./staging_service:/kb/deployment/lib/staging_service"
    networks:
      - kbase-dev
    dns:
      - 8.8.8.8
    environment:
      - KB_DEPLOYMENT_CONFIG=/kb/deployment/conf/deployment.cfg
      - FILE_LIFETIME=90
      # - SAVE_STRATEGY=SAVE_STRATEGY_TEMP_THEN_COPY
      # - SAVE_STRATEGY=SAVE_STRATEGY_SAVE_TO_DESTINATION
      # - CHUNK_SIZE=
    entrypoint:
      ["/kb/deployment/bin/entrypoint-dev.sh"]
