repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: '\.py$'
      - id: end-of-file-fixer
        files: '\.py$'
      - id: check-yaml
      - id: check-added-large-files
        files: '\.py$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args:
          - '--exclude=import_specifications/clients/baseclient.py'
