[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.mypy]
strict=true

[[tool.mypy.overrides]]
module = "aiohttp_cors.*"
ignore_missing_imports = true


[[tool.mypy.overrides]]
module = "globus_sdk.*"
ignore_missing_imports = true


[tool.autoflake]
remove_all_unused_imports = true
remove_unused_variables = true
quiet = true
