#!/usr/bin/env bash

PROJECT_DIRECTORY=${DIR:-$PWD}
echo "Project Directory: ${PROJECT_DIRECTORY}"
docker compose \
    -f "${PROJECT_DIRECTORY}/development/tools/runner/docker-compose.yml" \
    --project-name tools \
    run --rm runner "${@:1}"